# Generated by Django 4.1.7 on 2023-03-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('is_published', models.BooleanField(choices=[(True, 'published'), (False, 'not published')], default=False)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Котики', 'Котики'), ('Песики', 'Песики'), ('Книги', 'Книги'), ('Растения', 'Растения'), ('Мебель и интерьер', 'Мебель и интерьер')], max_length=20)),
            ],
        ),
    ]
