# Generated by Django 4.1.7 on 2023-03-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_location_id_user_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
    ]
