# Generated by Django 4.1.7 on 2023-03-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Местоположение', 'verbose_name_plural': 'Местоположения'},
        ),
    ]
